baseurl = "/"
title = "PratigyaICEP"
theme = "pratigya-theme"
#themesDir = "../.."
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-118778285-1"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Select Courses"
    url  = "/courses/"
    weight = 2
    identifier = "courses"
    HasChildren = true

[[menu.main]]
    name = "UPSC"
    url  = "/courses/upsc"
    weight = 5
    identifier = "upsc"
    parent = "courses"
    HasChildren = true

[[menu.main]]
    parent = "upsc"
    name = "About UPSC"
    url  = "/courses/upsc#about-upsc"
    weight = 1

[[menu.main]]
    parent = "upsc"
    name = "GS (Prelims-2019)"
    url  = "/classroom-courses/#fee-structure"
    weight = 4

[[menu.main]]
    parent = "upsc"
    name = "GS (Pre-cum-Mains-2019)"
    url  = "/classroom-courses/#fee-structure"
    weight = 4

[[menu.main]]
    parent = "upsc"
    name = "Classroom Course"
    url  = "/classroom-courses"
    weight = 5

[[menu.main]]
    parent = "upsc"
    name = "Postal Course"
    url  = "/postal-courses"
    weight = 6

[[menu.main]]
    parent = "upsc"
    name = "FAQ's"
#    url  = "/UPSC/GS-2019"
    weight = 7

[[menu.main]]
    name = "SPSC"
#    url  = "/courses/SPSC"
    weight = 6
    identifier = "spsc"
    parent = "courses"
    HasChildren = true

[[menu.main]]
    parent = "spsc"
    name = "About"
#    url  = "/SPSC/About"
    weight = 1

[[menu.main]]
    parent = "spsc"
    name = "GS Prelims"
#    url  = "/SPSC/classroom-course"
    weight = 2

[[menu.main]]
    parent = "spsc"
    name = "SPSC Classroom Course"
#    url  = "/SPSC/About"
    weight = 3

[[menu.main]]
    parent = "spsc"
    name = "SPSC Postal Course"
#    url  = "/SPSC/About"
    weight = 4


[[menu.main]]
    name = "SSC"
#    url  = "/courses/SSC"
    weight = 7
    identifier = "ssc"
    parent = "courses"
    HasChildren = true

[[menu.main]]
    parent = "ssc"
    name = "About SSC"
#    url  = "/UPPSC/bank-po"
    weight = 1

[[menu.main]]
    parent = "ssc"
    name = "SSC Classroom Course"
#    url  = "/UPPSC/bank-po"
    weight = 2

[[menu.main]]
    parent = "ssc"
    name = "SSC Postal Course"
#    url  = "/UPPSC/bank-po"
    weight = 3

[[menu.main]]
    parent = "ssc"
    name = "SSC Notification"
#    url  = "/UPPSC/bank-po"
    weight = 4

[[menu.main]]
    name = "BANKING"
#    url  = "/courses/BANKING"
    weight = 8
    identifier = "bank"
    parent = "courses"
    HasChildren = true

[[menu.main]]
    parent = "bank"
    name = "About Banking"
#    url  = "/UPPSC/apfc"
    weight = 1

[[menu.main]]
    parent = "bank"
    name = "Banking Classroom Course"
#    url  = "/UPPSC/cpo-si"
    weight = 2

[[menu.main]]
    parent = "bank"
    name = "Banking Postal Course"
#    url  = "/UPPSC/cpo-si"
    weight = 3

[[menu.main]]
    parent = "bank"
    name = "Banking Notification"
#    url  = "/UPPSC/cpo-si"
    weight = 4

[[menu.main]]
    name = "Other Exams"
#    url  = "/courses/BANKING"
    weight = 9
    identifier = "other"
    parent = "courses"
    HasChildren = true

[[menu.main]]
    parent = "other"
    name = "DSSSB"
#    url  = "/UPPSC/cpo-si"
    weight = 1


[[menu.main]]
    parent = "other"
    name = "CDS"
#    url  = "/UPPSC/cpo-si"
    weight = 2


[[menu.main]]
    parent = "other"
    name = "CAPF"
#    url  = "/UPPSC/cpo-si"
    weight = 3


[[menu.main]]
    parent = "other"
    name = "IB-ACIO"
#    url  = "/UPPSC/cpo-si"
    weight = 4


[[menu.main]]
    parent = "other"
    name = "APFC"
#    url  = "/UPPSC/cpo-si"
    weight = 5


[[menu.main]]
    parent = "other"
    name = "CPO-SI"
#    url  = "/UPPSC/cpo-si"
    weight = 6


[[menu.main]]
    parent = "other"
    name = "Territorial Army"
#    url  = "/UPPSC/cpo-si"
    weight = 7

[[menu.main]]
    name = "Resources"
#    url  = "/resources/"
    weight = 3
    identifier = "resources"
    HasChildren = true

[[menu.main]]
    name = "Syllabus"
#    url  = "/resources/syllabus"
    identifier = "syllabus"
    parent = "resources"
    weight = 1
    HasChildren = true

[[menu.main]]
    parent = "syllabus"
    name = "UPSC Syllabus"
#    url  = "/resources/syllabus/upsc-pre-syllabus"
    weight = 1

[[menu.main]]
    parent = "syllabus"
    name = "Optional Syllabus"
#    url  = "/resources/syllabus/upsc-mains-syllabus"
    weight = 2

[[menu.main]]
    parent = "syllabus"
    name = "SSC Syllabus"
#    url  = "/resources/syllabus/upsc-mains-syllabus"
    weight = 3

[[menu.main]]
    parent = "syllabus"
    name = "Bank Syllabus"
#    url  = "/resources/syllabus/upsc-mains-syllabus"
    weight = 4

[[menu.main]]
    parent = "syllabus"
    name = "Other Exams"
#    url  = "/resources/syllabus/upsc-mains-syllabus"
    weight = 5

[[menu.main]]
    name = "Booklet"
#    url  = "/resources/booklet"
    identifier = "booklet"
    parent = "resources"
    weight = 2
    HasChildren = true

[[menu.main]]
    parent = "booklet"
    name = "UPSC Pre & Mains"
#    url  = "/resources/booklet/upsc-pre"
    weight = 1

[[menu.main]]
    parent = "booklet"
    name = "SSC Booklet"
#    url  = "/resources/booklet/upsc-mains"
    weight = 2

[[menu.main]]
    parent = "booklet"
    name = "Banking Booklet"
#    url  = "/resources/booklet/upsc-mains"
    weight = 3

[[menu.main]]
    parent = "booklet"
    name = "Current Affairs"
#    url  = "/resources/booklet/upsc-mains"
    weight = 4

[[menu.main]]
    name = "Previous Years Papers"
#    url  = "/resources/previous-years-papers"
    identifier = "prev-year-paper"
    parent = "resources"
    weight = 3
    HasChildren = true

[[menu.main]]
    parent = "prev-year-paper"
    name = "UPSC Prelims"
#    url  = "/resources/previous-years-papers/upsc-prelims"
    weight = 1

[[menu.main]]
    parent = "prev-year-paper"
    name = "UPSC Mains"
#    url  = "/resources/previous-years-papers/upsc-mains"
    weight = 2

[[menu.main]]
    parent = "prev-year-paper"
    name = "UPSC Optional"
#    url  = "/resources/previous-years-papers/upsc-mains"
    weight = 3

[[menu.main]]
    parent = "prev-year-paper"
    name = "SSC Practice Papers"
#    url  = "/resources/previous-years-papers/upsc-mains"
    weight = 4

[[menu.main]]
    parent = "prev-year-paper"
    name = "Banking Practice Papers"
#    url  = "/resources/previous-years-papers/upsc-mains"
    weight = 5

[[menu.main]]
    name = "Student Info."
#    url  = "/resources/pratigya"
    identifier = "student"
    parent = "resources"
    weight = 4
    HasChildren = true

[[menu.main]]
    parent = "student"
    name = "Notifications"
#    url  = "/resources/pratigya/notifications"
    weight = 1

[[menu.main]]
    parent = "student"
    name = "Prospectus"
#    url  = "/resources/pratigya/propectus"
    weight = 2

[[menu.main]]
    parent = "student"
    name = "Online Registration"
#    url  = "/resources/pratigya/propectus"
    weight = 3

[[menu.main]]
    parent = "student"
    name = "Student Queries"
#    url  = "/resources/pratigya/propectus"
    weight = 4


# [[menu.main]]
#     name = "Resources"
#     identifier = "resources"
# #    url  = "/resources/"
#     weight = 3

#[[menu.main]]
#    name = "Blog"
#    url  = "/blog/"
#    weight = 4

#[[menu.main]]
#    name = "Alert"
#    url  = "/alert/"
#    weight = 5

[[menu.main]]
    name = "Enquiry"
    url  = "/contact/"
    weight = 6

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:your@email.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devows", "hugo", "go"]
    defaultDescription = "Site template made by devcows using hugo"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyC3YLYEQhmzQbLBGSOf9SuVUKvtbkRi2IY"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "your@email.com"

    about_us = "<p> <br/>201 Pal Mohan Mansiion <br/> 26/34 East Patel Nagar<br/> Near Oriental Bank of Commerce </br>Delhi-110008<br/> <br/>+91-84480 26019<br/>+91-84480 26018<br/>support@gmail.com</p>"
    copyright = "Copyright (c) 2018 - 2019, PratigyaICEP; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    address = """<p><strong>Pratigya ICEP</strong>
        <br>201 Pal Mohan Mansion
        <br>26/34 East Patel Nagar
        <br>Near Oriental Bank
        <br>New Delhi-110008
      </p>
      """
    latitude = 28.6441563
    longitude = 77.1756787

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[params.popup]
    link = "/register"
    img = "/img/popup.jpg"
    alt = "Register"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = ""

[params.topcourses]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Top Courses"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
